version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ./logs:/var/log/nginx

  php:
    image: php:fpm
    volumes:
      - ./html:/var/www/html
